repos:
  - repo: https://github.com/psf/black
    rev: 23.10.0  # Укажите актуальную версию black
    hooks:
      - id: black
        language_version: python3.12.6

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3.12.6
        args: [--profile, black]